name: Test Using Image

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test tkn
    runs-on: ubuntu-latest
    
    steps:
    - name: Create KinD cluster
      uses: engineerd/setup-kind@v0.4.0
      with:
          version: "v0.8.0"
    
    - name: Install Tekton
      run: kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
    
    - name: Use tkn
      uses: docker://gcr.io/tekton-releases/dogfooding/tkn
      with:
        entrypoint: /usr/local/bin/tkn
        args: pr ls
